### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by scjohnson1988** [rieck/perplex#10]
Does this script work on databases in the Windows version of Plex?  It took me a bit of troubleshooting/getting the progressbar and running everything with python2, but I am getting the below error running the script 

`Analyzing Plex database:
Traceback (most recent call last):
  File "./perplex.py", line 125, in <module>
    movies = build_db(args.plex)
  File "./perplex.py", line 43, in build_db
    year = row[2].split('-')[0]
`
I copied the database onto a Raspberry pi and re-ran it, but I'm getting the same errors.

**Comment by rieck** [comment]
As a side note, I am not actively maintaining this code as it has been inactive for years. If a significant change is required, I may not have the time to address it. Hopefully, only a quick fix is necessary.

**Comment by scjohnson1988** [comment]
I'm not very familiar at all with Python, so I just captured the command and output.  Image below is what I'm getting.

https://imgur.com/a/mZwYv0w

**Comment by windowslucker1121** [comment]
Try the newest build, it should work with a windows PMS
There could be a change that you need to make here:
https://github.com/rieck/perplex/blob/8fafe1d01ec7bbe94bd647897505eb709ee86f74/perplex.py#L108
to 
`dest, garbage = str(_).rsplit("\\", 1)`

Note:
when providing a direction in the arguments, you cant provide a directory with a space in it
like
`%localappdata%\Plex Media Server\Plug-in Support\Databases`
wont work, because Plex media server contains spaces.
just copy over the database folder to a directory like `C:\Users\USER\PMS_Database `
and it should work
