### ISSUE TITLE
Windows script support broke again

### ISSUE THREAD

**Issue by viperbe** [rieck/perplex#14]
This is what i get when running in windows.  Anyideas?

This is your code
``
    for row in db.execute(query):
        title = convert([x for x in row[1] if x not in del_chars])
        year = datetime.date.fromtimestamp(row[2]).strftime("%Y")
        movies[row[0]] = (title, year, [])

THis is what i get

```
PS C:\Users\soyvi\Downloads\perplex-master\perplex-master> python perplex.py --save movies.db --plex "C:\Users\soyvi\AppData\Local\Plex Media Server"
Analyzing Plex database:
Found Database: C:\Users\soyvi\AppData\Local\Plex Media Server\Plug-in Support\Databases\com.plexapp.plugins.library.db
Traceback (most recent call last):
  File "C:\Users\soyvi\Downloads\perplex-master\perplex-master\perplex.py", line 191, in <module>
    movies = build_db(args.plex)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soyvi\Downloads\perplex-master\perplex-master\perplex.py", line 50, in build_db
    year = datetime.date.fromtimestamp(row[2]).strftime("%Y")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
```

**Comment by viperbe** [comment]
After fixing that i got  - 

``Analyzing Plex database:
Found Database: C:\Users\soyvi\AppData\Local\Plex Media Server\Plug-in Support\Databases\com.plexapp.plugins.library.db
Traceback (most recent call last):
  File "C:\Users\soyvi\Downloads\perplex-master\perplex-master\perplex.py", line 125, in <module>
    movies = build_db(args.plex)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soyvi\Downloads\perplex-master\perplex-master\perplex.py", line 49, in build_db
    title = convert([x for x in row[1] if x not in del_chars])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\soyvi\Downloads\perplex-master\perplex-master\perplex.py", line 89, in convert
    title = title.replace(c, '_')

**Comment by viperbe** [comment]
Here is the final script that will fix it


#!/usr/bin/env python
# -*- coding: utf8 -*-
# Perplex - A Movie Renamer for Plex Metadata
# Copyright (c) 2015 Konrad Rieck (konrad@mlsec.org)

import argparse
import datetime
import gzip
import json
import os
import shutil
import sqlite3
import sys

import progressbar as pb

# Chars to remove from titles
del_chars = '.'
forbiddenCharsInNames = '\\', '/', ':', '*', '?', '"', '<', '>', '|'


def find_db(plex_dir, name):
    """ Search for database file in directory """

    for root, dirs, files in os.walk(plex_dir, onerror=errorOut):
        for file in files:
            if file == name:
                databasePath = os.path.join(root, file)
                print("Found Database: " + databasePath)
                return databasePath

    return None


def build_db(plex_dir, movies={}):
    """ Build movie database from sqlite database """

    print("Analyzing Plex database:")
    dbfile = find_db(plex_dir, "com.plexapp.plugins.library.db")

    db = sqlite3.connect(dbfile)

    # Select only movies with year
    query = """
        SELECT id, title, originally_available_at FROM metadata_items
        WHERE metadata_type = 1 AND originally_available_at """

    for row in db.execute(query):
        title = convert(''.join([x for x in row[1] if x not in del_chars]))
        
        if row[2] is not None:
            try:
                year = datetime.date.fromtimestamp(row[2]).strftime("%Y")
            except (OSError, ValueError):
                year = 'N/A'  # Handle invalid timestamp values
        else:
            year = 'N/A'

        movies[row[0]] = (title, year, [])

    # Get files for each movie
    query = """
        SELECT mp.file FROM media_items AS mi, media_parts AS mp
        WHERE mi.metadata_item_id = %s AND mi.id = mp.media_item_id """

    files = 0
    for id in movies:
        try:
            for file in db.execute(query % id):
                movies[id][2].append(file[0])
                files += 1
        except Exception as e:
            errorOut(e)
    db.close()
    print(("%d movies and %d files" % (len(movies), files)))

    return movies


def print_doubles(files):
    print("Found multiple files for the same movie")
    for f in files:
        print(f)


def convert(title):
    """ Convert title to a valid file name """
    for c in forbiddenCharsInNames:
        title = title.replace(c, '_')
    return title


def errorOut(msg):
    """ Print error message and exit """
    print("Error: " + str(msg))
    sys.exit(-1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Perplex - A Movie Renamer for Plex Metadata')

    parser.add_argument('--plex', metavar='<dir>', type=str,
                        help='path to Plex Media Server directory')
    parser.add_argument('--load', metavar='<file>', type=str,
                        help='load metadata from file')
    parser.add_argument('--save', metavar='<file>', type=str,
                        help='save metadata to file')
    parser.add_argument('--dest', metavar='<dir>', type=str,
                        help='destination directory for renamed files')
    parser.add_argument('--dry', action='store_true',
                        help='show dry run of what will happen')
    parser.add_argument('--justRename', metavar='<dir>', type=str,
                        help='renames the original files instead of copying them - provide the <dir> to rename files in')
    parser.add_argument('--printDoubles', action='store_true',
                        help='Print double movies with locations if found')

    parser.set_defaults(dry=False)
    parser.set_defaults(printDoubles=False)
    args = parser.parse_args()

    if (args.justRename is not None and args.justRename is not False) and (args.dest is not None):
        errorOut("Can't provide --dest and --justRename Args at the same time")

    if args.plex:
        movies = build_db(args.plex)
    elif args.load:
        print(("Loading metadata from " + args.load))
        movies = json.load(gzip.open(args.load))
    else:
        print("Error: Provide a Plex database or stored database.")
        sys.exit(-1)

    if args.save:
        print(("Saving metadata to " + args.save))
        with gzip.open(args.save, 'wt', encoding='ascii') as file:
            json.dump(movies, file)

    if args.printDoubles:
        print_doubles = True
    else:
        print_doubles = False

    if args.justRename:
        print(("Building file mapping for each Movie itself"))
        mapping = build_map(movies, None, print_doubles, args.justRename)
        print(("Start Renaming the files in their original path"))
        rename(mapping, args.dry)
    elif args.dest:
        print(("Building file mapping for " + args.dest))
        mapping = build_map(movies, args.dest, print_doubles)
        print(("Copying renamed files to " + args.dest))
        copy_rename(mapping, args.dest, args.dry)
    else:
        if args.printDoubles:
            print("Print doubles can only be used when building the mapping, try it with the --dry parameter")
